### ISSUE TITLE
slider create error installing presto on head node

### ISSUE THREAD

**Issue by smith-m** [dharmeshkakadia/presto-hdinsight#8]
The installation script action fails on both head nodes in Hadoop HDInsight 3.5 and 3.6

From hn0

>slider create presto1 --template appConfig-default.json --resources resources-default.json
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/custom_actions/scripts/run_customscriptaction.py", line 194, in <module>
    ExecuteScriptAction().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 314, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/custom_actions/scripts/run_customscriptaction.py", line 179, in actionexecute
    ExecuteScriptAction.execute_bash_script(bash_script, scriptpath, scriptparams)
  File "/var/lib/ambari-agent/cache/custom_actions/scripts/run_customscriptaction.py", line 149, in execute_bash_script
    raise Exception("Execution of custom script failed with exit code",exitcode)
Exception: ('Execution of custom script failed with exit code', 70)

>2017-05-04 23:35:59,642 [main] INFO  client.SliderClient - Error Component WORKER has negative instance count: -1 validating application instance definition 

> 2017-05-04 21:35:17,539 [main] ERROR main.ServiceLauncher - Component WORKER has negative instance count: -1
2017-05-04 21:35:17,542 [main] INFO  util.ExitUtil - Exiting with status 70
2017-05-04 21:35:17,549 [pool-1-thread-1] INFO  impl.MetricsSystemImpl - Stopping azure-file-system metrics system...
2017-05-04 21:35:17,550 [azurefs2] INFO  impl.MetricsSinkAdapter - azurefs2 thread interrupted.
2017-05-04 21:35:17,550 [pool-1-thread-1] INFO  impl.MetricsSystemImpl - azure-file-system metrics system stopped.
2017-05-04 21:35:17,550 [pool-1-thread-1] INFO  impl.MetricsSystemImpl - azure-file-system metrics system shutdown complete.
('Start downloading script locally: ', u'https://raw.githubusercontent.com/dharmeshkakadia/presto-hdinsight/master/installpresto.sh')
Fromdos line ending conversion successful
('Unexpected error:', "('Execution of custom script failed with exit code', 70)")
Removing temp location of the script
Command failed after 1 tries

Does this component of the resource-default.json need to change?

`
"WORKER" : {
      "yarn.role.priority" : "2",
      "yarn.component.instances" : "-1",
      "yarn.memory" : "24576",
      "yarn.component.placement.policy" : "1"
    }
`

**Comment by dharmeshkakadia** [comment]
You need atleast 3 workernodes in the cluster. As mentioned in the README, on a N worker node cluster, you will have N-2 presto worker nodes and 1 coordinator node.

**Comment by dharmeshkakadia** [comment]
@smith-m Were you able to try it on a larger cluster ?

**Comment by smith-m** [comment]
Yes, this script worked on 3.5 and 3.6 for clusters with 4+ workers. 3 was not enough.
